### PR TITLE
Using yargs 10.0.3 to parse dashed args correctly

### PR DESCRIPTION
**Pull request by vadim-galeev**
Fix for https://github.com/EatonGMBD/imp-central-impt/issues/8 as agreed in the issue' comments (workaround 1).

### CODE REVIEW

**Comment by deldrid1** [comment]
@vadim-galeev - looks like you have some merge conflicts committed?

**Comment by vadim-galeev** [comment]
@deldrid1, I have back-merged develop branch into bugfix/Issue8-Parsing-dashed-args-error after pull request #12 was merged into develop.

**Comment by alexey-nbl** [comment]
@deldrid1 @mm-gmbd 
The second issue we submitted against yargs (https://github.com/yargs/yargs-parser/issues/254) has no reaction for more than a week. Seems, no reason to wait more...
Let's apply the workaround 1) described here https://github.com/EatonGMBD/imp-central-impt/issues/8
Please review/approve this PR for that.

**Review by mm-gmbd — APPROVED** [review]

**Comment by mm-gmbd** [comment]
Approved! @alexey-nbl, can you create an issue that references the open issue on yargs to update to latest yargs once it is fixed?

**Comment by alexey-nbl** [comment]
I think, we may keep the existing one (https://github.com/EatonGMBD/imp-central-impt/issues/8) opened for that.

**Comment by mm-gmbd** [comment]
That bug is fixed with `10.0.3`, no? I'm fine with using #8, but we should update the title in that case.

**Comment by alexey-nbl** [comment]
https://github.com/EatonGMBD/imp-central-impt/issues/19 is submitted.

**Pull request merged**
