### PR TITLE
Add `impt build generate` command for artifacts

### PR DESCRIPTION
**Pull request by xinyi-joffre**
The current implementation of `impt build deploy` combines the preBuild, build, postBuild, and deploy steps all into one. This makes it difficult to run in PR builds or CI builds to get a reproducible artifact. We also don't want to accidentally deploy to same DG in parallel for PR build validation.

This PR adds a command for `impt build generate` which will only run the preBuild, build, and postBuild steps, but not deploy the code to imp central. Generate command requires GitHub access token in order to pull the dependencies.

Future iterations of this may include a configurable output path for the assets to make it easier to bundle.

This PR should keep the current functionality of `impt build deploy` the same (but refactors out the common code).

Troubleshooting:
If running without `impt auth login` or a valid impt.auth file, you will need these environment variables set:

GITHUB_TOKEN=<VALID TOKEN>
IMPT_LOGINKEY='loginkey';
IMPT_USER='user';
IMPT_ENDPOINT='endpoint';

The IMPT variables can be kept as fake values since we are not actually talking to imp central when generating assets.

### CODE REVIEW

**Comment by xinyi-joffre** [comment]
@mm-gmbd, @deldrid1, I'm not very familiar with this tool, but it works for me locally. Let me know if have any issues with it!

**Review by NasibMansour — APPROVED** [review]
This looks great! I can't try it locally because of network issues for impt but it's good!

**Comment by mm-gmbd** [comment]
image

I've wanted this feature for so long -- thanks for adding!

**Review by mm-gmbd — APPROVED** [review]

**Comment by mm-gmbd** [comment]
I'll go ahead and merge 👍

**Pull request merged**
